:sparkles: Add support for multiple slices

diff --git a/dissect b/dissect
--- a/dissect
+++ b/dissect
@@ -3,13 +3,24 @@
 #
 # A helper script to generate skalpel visualisation files and open the
 # visualisation webapp
+#
+# Note: This file combines all of the files generated by skalpel into
+# a single JSON file containing a top-level key "data" which value
+# is the array of the combined files.
+#
 
 set -eu
 
 # Require 1 args (source file)
-if [ ! ${#} -eq 1 ] ; then
+if [[ ! ${#} -eq 1 ]] ; then
 	echo "Usage: ./dissect <source_file>"
 	exit 1
+fi
+
+# Check file exists
+if [ ! -f ${1} ] ; then
+  echo "File Not Found [${1}]"
+  exit 1
 fi
 
 # macOS or Linux?
@@ -26,7 +37,19 @@ SKALPEL_CMD="skalpel -z ${1} -b 1 ${1}"
 # Run skalpel
 ${SKALPEL_CMD}
 
-${OPEN} http://localhost:1337
+rm ${1}.viz.json
+echo "{ \"data\": [" > ${1}.viz.json
+# Combine output files!
+for FILE in ${1}-*.viz.json; do
+	cat ${FILE} >> ${1}.viz.json.tmp
+	echo "," >> ${1}.viz.json.tmp
+done
+sed '$d' ${1}.viz.json.tmp >> ${1}.viz.json
+echo "]}" >> ${1}.viz.json
+
+rm ${1}.viz.json.tmp ${1}-*.viz.json
+
+${OPEN} http://localhost:1337/
 
 # Start python server
 python3 -m http.server 1337
